version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: hackathon_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: hackathon
      POSTGRES_PASSWORD: hackathon
      POSTGRES_DB: hackathon
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
